name: Notion auto backup 🔐

on: [push]

jobs:
  copy_project:
    name: Copy project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: .
          target: "./notion_auto_backup/notion_auto_backup"

  send_message_final:
      runs-on: ubuntu-latest
      needs: copy_project
      steps:
        - name: send message
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: ${{ github.workflow }} - Успешный деплой!
